global:
  name: consul
  datacenter: dc1
  tls:
    enabled: true
  federation:
    enabled: true
    createFederationSecret: true
  acls:
    manageSystemACLs: false
    createReplicationToken: false
connectInject:
  enabled: true
  default: true
controller:
  enabled: true
server:
  replicas: 1
meshGateway:
  enabled: true
  replicas: 1
